apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daocloud
    component: daocloud-sample-dev
    tier: backend
  name: daocloud-sample-dev
  namespace: mabing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: daocloud
      component: daocloud-sample-dev
      tier: backend
  template:
    metadata:
      labels:
        app: daocloud
        component: daocloud-sample-dev
        tier: backend
    spec:
      containers:
        - image: release-ci.daocloud.io/demo/http-hello:latest
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: daocloud-sample
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: daocloud
    component: daocloud-sample-dev
  name: daocloud-sample-dev
  namespace: mabing
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: daocloud
    component: daocloud-sample-dev
    tier: backend
  sessionAffinity: None
  type: ClusterIP
