apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daocloud-java
    component: daocloud-sample-dev-java
    tier: backend-java
  name: daocloud-sample-dev-java
  namespace: mabing
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: daocloud-java
      component: daocloud-sample-dev-java
      tier: backend-java
  template:
    metadata:
      labels:
        app: daocloud-java
        component: daocloud-sample-dev-java
        tier: backend-java
    spec:
      containers:
        - image: release-ci.daocloud.io/demo/java-simple-http:latest
          readinessProbe:
            httpGet:
              path: /test
              port: 8000
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: daocloud-sample
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: daocloud
    component: daocloud-sample-dev-java
  name: daocloud-sample-dev-java
  namespace: mabing
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 32766
  selector:
    app: daocloud-java
    component: daocloud-sample-dev-java
    tier: backend-java
  sessionAffinity: None
  type: NodePort