FROM golang:1.16.15 as builder
RUN mkdir /root/project
COPY go.mod main.go /root/project/
RUN cd /root/project && go build -o simple-http-server main.go

FROM ubuntu:22.04
COPY --from=builder /root/project/simple-http-server /
CMD  [ "/simple-http-server" ]
