apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: '1234567'
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  annotations:
    #tekton.dev/git-0: http://git.k8s.local
    tekton.dev/git-0: https://gitlab.daocloud.cn
type: kubernetes.io/basic-auth
stringData:
  username: bing.ma
  password: oongie0seRug#oo
