apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: 10.6.182.195:5000/ubuntu:latest
      #command: 
      #  - bash
      #  - -c
      #  - echo "Hello,world!"
      script: | 
        #!/usr/bin/bash
        echo "hello world"
