apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: golang-binding
spec:
  params:
    - name: gitrevision
      value: $(body.checkout_sha)
    - name: gitrepositoryurl
      value: $(body.repository.git_http_url)
